# Generated by Django 3.2.4 on 2021-06-13 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210613_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
