# Generated by Django 3.2.4 on 2021-06-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anime_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
